const GRID_COLUMN_COUNT = 24;
const MARGIN_BETWEEN_WIDGETS = 10;
const GRID_ROW_HEIGHT = 50;
const BREAKPOINT_SIZES = { lg: 50 };

export { BREAKPOINT_SIZES, GRID_COLUMN_COUNT, GRID_ROW_HEIGHT, MARGIN_BETWEEN_WIDGETS };
