const GRID_COLUMN_COUNT = 24;
const GRID_ROW_HEIGHT = 50;
const GAP_FROM_WALLS = 10;
const GAP_BETWEEN_WIDGETS = 10;
const GRID_COLOR = '#999';
const BREAKPOINT_SIZES = { lg: 50 };

export { BREAKPOINT_SIZES, GAP_BETWEEN_WIDGETS, GAP_FROM_WALLS, GRID_COLOR, GRID_COLUMN_COUNT, GRID_ROW_HEIGHT };
